-- Daily Visitors table for Deeam
-- Run this in Supabase SQL Editor to create the table

CREATE TABLE IF NOT EXISTS public.daily_visitors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id TEXT NOT NULL,
  visited_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create unique index to prevent duplicate entries (same visitor, same day)
CREATE UNIQUE INDEX IF NOT EXISTS daily_visitors_unique_idx
  ON public.daily_visitors (visitor_id, visited_date);

-- Enable Row Level Security
ALTER TABLE public.daily_visitors ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read (count today's visitors)
CREATE POLICY "Anyone can count daily visitors" ON public.daily_visitors
  FOR SELECT USING (true);

-- Allow anyone to insert (record a visit)
CREATE POLICY "Anyone can record a visit" ON public.daily_visitors
  FOR INSERT WITH CHECK (true);

-- Allow anyone to upsert (prevent duplicate insert attempts)
CREATE POLICY "Anyone can upsert daily visit" ON public.daily_visitors
  FOR INSERT WITH CHECK (true);

-- RLS policy for update (allow upsert logic)
CREATE POLICY "Anyone can upsert daily visit (update)" ON public.daily_visitors
  FOR UPDATE USING (true);
