-- Guestbook table for Deeam
-- Run this in Supabase SQL Editor to create the table

CREATE TABLE IF NOT EXISTS public.guestbook (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nickname TEXT NOT NULL CHECK (char_length(nickname) <= 30),
  message TEXT NOT NULL CHECK (char_length(message) <= 500),
  avatar_color TEXT DEFAULT '#667eea',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  count BIGINT
);

-- Enable Row Level Security
ALTER TABLE public.guestbook ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read messages
CREATE POLICY "Anyone can read guestbook" ON public.guestbook
  FOR SELECT USING (true);

-- Allow anyone to insert messages
CREATE POLICY "Anyone can post to guestbook" ON public.guestbook
  FOR INSERT WITH CHECK (true);

-- Optionally, allow update/delete only with auth (not needed for basic guestbook)
